name: Deploy Frontend
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ['frontend/**']
  push:
    branches: [master]
    paths: ['frontend/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref == 'refs/heads/master' && 'production' || 'staging' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          working-directory: ./frontend
          vercel-args: ${{ github.ref == 'refs/heads/master' && '--prod' || '' }}