name: Deploy Backend
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths: ['backend/**', 'docker-compose.yml']
  push:
    branches: [master]
    paths: ['backend/**', 'docker-compose.yml']

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.ref == 'refs/heads/master' && 'production' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: railwayapp/actions-deploy@v1
        with:
          railway-token: ${{ secrets.RAILWAY_TOKEN }}
          project-id: ${{ secrets.RAILWAY_PROJECT_ID }}
          service-id: ${{ github.ref == 'refs/heads/master' && secrets.RAILWAY_SERVICE_ID_PRODUCTION }}