name: GitHub Actions Build
run-name: ${{ github.actor }} app Build

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'frontend/**'
jobs:
  app-build:
    # (extra safety) ensure the PR is open
    if: ${{ github.event.pull_request.state == 'open' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: |
           pwd
           npm install
      - name: Run build
        run: npm run build