name: Playwright Tests with Mocked Backend

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  test:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run-mocks')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
          npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          cd frontend
          npx playwright test
