name: Playwright Tests with Backend via Docker

on:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  test:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'run-integration')
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Start services
        run: |
          docker-compose up -d
      - name: Wait for frontend
        run: |
          timeout 10 bash -c 'until curl -sSf http://localhost:3000 >/dev/null; do sleep 2; done'
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
          npx playwright install --with-deps
      - name: Run Playwright tests
        run: |
          cd frontend
          npx playwright test --config=playwright.docker.config.ts
      - name: Stop services
        if: always()
        run: docker-compose down
