name: GitHub Actions Unit Tests
run-name: ${{ github.actor }} Unit tests run
on: 
  push:
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
