name: GitHub Actions Unit Tests Backend
run-name: ${{ github.actor }} Unit tests run Backend
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'backend/**'

jobs:
  unit-tests:
    if: ${{ github.event.pull_request.state == 'open' && github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}   # 👈 ensure 'backend' (at repo root) is importable
        run: |
          pwd
          ls -la
          python -c "import sys; print('PYTHONPATH OK?', any(p.endswith('survey_web_site') for p in sys.path), '\nTOP PATHS:', sys.path[:3])"
          python -m pytest backend/tests 
