name: GitHub Actions Unit Tests
run-name: ${{ github.actor }} Unit tests run

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  unit-tests:
    # (extra safety) ensure the PR is open
    if: ${{ github.event.pull_request.state == 'open' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Change directory
        run: cd frontend

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
