name: GitHub Actions Unit Tests Backend
on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'backend/**'

env:
  WORKDIR: '/backend'

jobs:
  unit-tests:
    if: ${{ github.event.pull_request.state == 'open' && github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r ${{ env.WORKDIR }}/requirements.txt

      - name: Run tests
        run: |
          pwd                   # should print .../survey_web_site
          python -m pytest ${{ env.WORKDIR }}/tests 
