name: GitHub Actions Unit Tests Backend
run-name: ${{ github.actor }} Unit tests run Backend

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'backend/**'
env:                    
  WORKDIR: ./backend

jobs:
  unit-tests:
    # (extra safety) ensure the PR is open
    if: ${{ github.event.pull_request.state == 'open' && github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKDIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest ${{ env.WORKDIR }}/tests
